#pragma once

// From glfw3.h
#define MINT_MOUSE_BUTTON_1      0
#define MINT_MOUSE_BUTTON_2      1
#define MINT_MOUSE_BUTTON_3      2
#define MINT_MOUSE_BUTTON_4      3
#define MINT_MOUSE_BUTTON_5      4
#define MINT_MOUSE_BUTTON_6      5
#define MINT_MOUSE_BUTTON_7      6
#define MINT_MOUSE_BUTTON_8      7
#define MINT_MOUSE_BUTTON_LAST   MINT_MOUSE_BUTTON_8
#define MINT_MOUSE_BUTTON_LEFT   MINT_MOUSE_BUTTON_1
#define MINT_MOUSE_BUTTON_RIGHT  MINT_MOUSE_BUTTON_2
#define MINT_MOUSE_BUTTON_MIDDLE MINT_MOUSE_BUTTON_3
